### ISSUE TITLE
Restructure map data

### ISSUE THREAD

**Issue by ecumene** [JarrodM-M/PokerDice#3]
Instead of the board being a for loop, generate an array of arrays and map over them in react to divs.

![Screen Shot 2022-03-02 at 7 54 58 PM](https://user-images.githubusercontent.com/6249465/156466661-cc8fd6a7-cf3c-4994-a841-11d497fc2545.png)

Remove these lines of code
https://github.com/JarrodM-M/PokerDice/blob/0cfa4e16e65fa9dcd534dcbb9b4fcdbcf33f50c7/pokerdice/src/components/Gameboard.js#L10

Replace with map over arrays then map over those arrays then map to divs

**Comment by JarrodM-M** [comment]
Done son.
