### ISSUE TITLE
testSliceX and testSliceY could be the same function

### ISSUE THREAD

**Issue by ecumene** [JarrodM-M/pokerdice#37]
In the case of X: Call the function with the board as input
In the case of Y: Call the function with this as input:

https://github.com/JarrodM-M/pokerdice/blob/b09153da4015ce6a2034b3ae7b159b5effcddb1f/src/components/Gameboard.test.js#L1382

**Comment by JarrodM-M** [comment]
In X: ` subElement.y - lastY == 1` is different from
In Y :  `subElement.x - lastX == 1`

Can't define these subElements as props in a bigger function that will work on both X and Y tests.
